apiVersion: v1
kind: Pod
metadata:
  name: jenkins-docker-hub
  labels:
    app: jenkins-docker-hub
spec:
  containers:
    - name: jenkins-docker-hub
      image: chaimakh/jenkins-docker-hub:latest
      ports:
        - containerPort: 8080
