kind: Service
apiVersion: v1
metadata:
  name: jenkins-docker-hub
spec:
  selector:
    app: jenkins-docker-hub
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 32220
  type: NodePort 
